apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: -workflow
build:
  artifacts:
  - image: building-apps
    context: src
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
    - k8s/service.yaml
